# Importing the Libraries

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.0.0'

# Part-1--> Data Preprocessing

# Importing the dataset 

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding the Categorical Data

# Label Encoding the Gender Column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# One Hot Encoding the "Geography" Column 

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x=np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the Dataset into train set and test set 

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# Part-2--> Building the ANN

# Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

# Adding the Input Layer and first Hidden Layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # relu is the name for rectifier function

# Adding the Second Hidden Layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the Output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3--> Training the ANN 

# Compiling the ANN

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Training the ANN on the Training set 

In [17]:
ann.fit(x_train, y_train, batch_size = 32, epochs=100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 93us/sample - loss: 0.5618 - accuracy: 0.7554
Epoch 2/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.4639 - accuracy: 0.7954
Epoch 3/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.4395 - accuracy: 0.7996
Epoch 4/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.4284 - accuracy: 0.8092
Epoch 5/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.4195 - accuracy: 0.8149
Epoch 6/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.4108 - accuracy: 0.8229
Epoch 7/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3993 - accuracy: 0.8296
Epoch 8/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3870 - accuracy: 0.8344
Epoch 9/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3789 - accuracy: 0.8372
Epoch 10/100
8000/8000 [

8000/8000 [==============================] - 0s 28us/sample - loss: 0.3349 - accuracy: 0.8631
Epoch 78/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3348 - accuracy: 0.8637
Epoch 79/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3350 - accuracy: 0.8641
Epoch 80/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3348 - accuracy: 0.8655
Epoch 81/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3351 - accuracy: 0.8650
Epoch 82/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3350 - accuracy: 0.8640
Epoch 83/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3347 - accuracy: 0.8658
Epoch 84/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3352 - accuracy: 0.8651
Epoch 85/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3350 - accuracy: 0.8646
Epoch 86/100
8000/8000 [==========================

# Predicting a new result

In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.02895839]]


# Predicting the test set results

In [19]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 203  202]]


0.8655